# Generated by Django 4.1.2 on 2022-10-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名稱')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='商品描述')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='商品價格')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='修改日期')),
            ],
        ),
    ]
